### ISSUE TITLE
Blob() breaking change in 7.3.4 using Karma + PhantomJS

### ISSUE THREAD

**Issue by joaovieira** [danialfarid/ng-file-upload#1027]
@danialfarid just wanted to let you know that 7.3.4 introduced `Blob()` which is only supported in the "new" PhantomJS 2.0 (https://github.com/ariya/phantomjs/issues/11013). Karma does not have (official) support for PhantomJS 2.0 yet (https://github.com/karma-runner/karma-phantomjs-launcher/issues/56). So this may cause an unexpected breaking change that could be mentioned in a migration guide?

Thanks. 

We're staying with 7.3.3 for the time being :)

**Comment by danialfarid** [comment]
Added a check for Blob function in version 7.3.9. Should fix this issue.

**Comment by joaovieira** [comment]
@danialfarid 7.3.9 did not fix this.

Here's a stacktrace:
```
TypeError: '[object BlobConstructor]' is not a constructor (evaluating 'new Blob()')
            at /Users/joaovieira/Documents/.../app/bower_components/ng-file-upload/ng-file-upload.js:32
            at /Users/joaovieira/Documents/.../app/bower_components/ng-file-upload/ng-file-upload.js:35
            at invoke (/Users/joaovieira/Documents/.../app/bower_components/angular/angular.js:4476)
```

Changing https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L32 to:
```
return window.Blob && Blob.slice;
```

Did the trick. 

MDN Blob - https://developer.mozilla.org/en-US/docs/Web/API/Blob

**Comment by danialfarid** [comment]
The changed didn't get in this version, will be fixed in the next version

**Comment by danialfarid** [comment]
Fixed in version 8.0.1
