### ISSUE TITLE
Progress not triggered with pace.js

### ISSUE THREAD

**Issue by krbnr** [danialfarid/ng-file-upload#1123]
The upload process works fine but the progress callback is not being called.

The order of the imports seems to be OK...

<script src="bower_components/angular/angular.js"></script>
<script src="bower_components/ng-file-upload/ng-file-upload-shim.js"></script>
<script src="bower_components/ng-file-upload/ng-file-upload.js"></script>
<script src="bower_components/PACE/pace.js"></script>

The code...

file.upload = Upload.upload({
    url: 'https://angular-file-upload-cors-srv.appspot.com/upload',
    data: {file: file}
});
file.upload.then(function(resp) {
    // file is uploaded successfully
    console.log(resp.data);
}, function(resp) {
    // handle error
}, function(evt) {
    // progress notify
    console.log('progress triggered');
});

If I remove PACE from the imports it's called fine.

Any suggestion?

Note: I'm using controller As style.

**Comment by danialfarid** [comment]
See this: https://github.com/danialfarid/ng-file-upload/issues/561

**Comment by krbnr** [comment]
I've already checked that issue because If i rearrange the order to have pace.js imported at first the upload process won't work at all, but still no luck with the progress callback.

Thanks.

**Comment by danialfarid** [comment]
If you create a jsfiddle showing the error I will investigate more.

**Comment by shedar** [comment]
The issue is type checking https://github.com/danialfarid/ng-file-upload/blob/master/src/upload.js#L70
Pace replaces XMLHttpRequest https://github.com/HubSpot/pace/blob/master/pace.js#L437 so instanceOf fails and function returns before progress listener set.

**Comment by danialfarid** [comment]
The XMLHttpRequest instance should still be of XMLHttpRequest type so instance of should pass since pace.js just replaces the whole thing. Try to load angular after pace.js.

**Comment by shedar** [comment]
here is a jsfiddle http://jsfiddle.net/huhjo9jm/141/
pace added as a last script (can be checked in source of http://fiddle.jshell.net/huhjo9jm/141/show/ )
So you can see that progress doesn't work due to described reason

**Comment by shedar** [comment]
and http://jsfiddle.net/huhjo9jm/142/ with pace as a first script - doesn't work as well, even more - it generates exceptions

**Comment by aneesv** [comment]
:+1:  Have same issue

**Comment by danialfarid** [comment]
Fixed at 11.2.0

**Comment by ulion** [comment]
I am using 11.2.3, with pace, but the progress callback is still not get called?

**Comment by ulion** [comment]
The most interest part is that, if I using the minimized ng-file-upload js, it does not produce the error at all. but the non-minimized js will always produce the error and fail the upload

**Comment by ulion** [comment]
there is a workaround in #832, but may not fully works, but at least not worse.

**Comment by Tronix117** [comment]
The only thing you need to do to get this working is to add the following code somewhere after pace has been loaded:

`XMLHttpRequest.prototype = Object.getPrototypeOf(new XMLHttpRequest);`
