### ISSUE TITLE
IE 11 clipboardData is undefined

### ISSUE THREAD

**Issue by moneytree-doug** [danialfarid/ng-file-upload#1212]
I believe IE has the clipboardData in the window, so it throws an error when trying to find it on the event.

**Comment by danialfarid** [comment]
What are the steps to reproduce?

**Comment by danialfarid** [comment]
Should probably be fixed at 11.2.0

**Comment by aeslinger0** [comment]
This is still an issue in 12.0.4. Steps to reproduce are just trying to paste text into an input that is wrapped in a div that has this directive on it. `evt.clipboardData` and `evt.originalEvent` are both undefined.
![image](https://cloud.githubusercontent.com/assets/8813038/21203725/6973a460-c219-11e6-8a90-6fa320ff8632.png)

**Comment by danialfarid** [comment]
@aeslinger0 try with the latest version.

**Comment by aeslinger0** [comment]
@danialfarid This is still a problem in version 12.2.13. I think it's now line 1969 that is the problem:

`extractFilesAndUpdateModel(evt.clipboardData || evt.originalEvent.clipboardData, evt, 'pasteUrl');`

I think adding `|| window.clipboardData` as another fallback should fix it. My coworker will be submitting a PR with a fix. Please keep an eye out for it.
