### ISSUE TITLE
Choosing a large video file freezes browser

### ISSUE THREAD

**Issue by bgold0** [danialfarid/ng-file-upload#1242]
When I choose a large video file (500MB+) to upload with the below HTML, the browser start to hang and freezes up. I then have to close my tab and restart. Do you know what the issue may be? This does not seem to be happening to to large .rar files so it must be something to do with video.

    <div id="upload_button" ngf-select ng-model="files" ngf-multiple="true" ngf-max-size="'3GB'" ngf-max-total-size="'3GB'" ngf-keep="'distinct'">ADD FILES</div>

Here is my controller as well:

    $scope.$watch('files', function () {
        console.log($scope.files);
    });
    $scope.$watch('file', function () {
        if ($scope.file != null) {
            $scope.files = [$scope.file]; 
        }
    });
    $scope.log = '';

    $scope.upload = function (files) {

        if (files && files.length) {
            for (var i = 0; i < files.length; i++) {
              var file = files[i];
              if (!file.$error) {
                Upload.upload({
                    url: 'https://angular-file-upload-cors-srv.appspot.com/upload',
                    data: {
                      username: $scope.username,
                      file: file  
                    }
                }).progress(function (evt) {
                    var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                    $scope.log = 'progress: ' + progressPercentage + '% ' +
                                evt.config.data.file.name + '\n' + $scope.log;
                }).success(function (data, status, headers, config) {
                    $timeout(function() {
                        $scope.log = 'file: ' + config.data.file.name + ', Response: ' + JSON.stringify(data) + '\n' + $scope.log;
                    });
                });
              }
            }
        }
    };

**Comment by danialfarid** [comment]
If not the file is too big to fit in the browsers memory to be uploaded. Try to upload it in chunks,

**Comment by bgold0** [comment]
I don't think this is the case @danialfarid. *Note: this is before being uploaded*.

If choose a zip/rar file that is 800MB, everything is fine. If I choose a mp4/mov that is 800MB, it freezes.

**Comment by danialfarid** [comment]
Do you have ngf-src in your html?

**Comment by danialfarid** [comment]
or validation on the duration?

**Comment by bgold0** [comment]
I don't believe so. The following is my only HTML.

    <div id="upload_button" ngf-select ng-model="files" ngf-multiple="true" ngf-max-size="'3GB'" ngf-max-total-size="'3GB'" ngf-keep="'distinct'">ADD FILES</div>
    <div id="item_container" ng-repeat="f in files"></div>
    <div ngf-drop ngf-select ng-model="files" class="dropzone-highlight-container" ngf-drag-over-class="'showdropzone'" ngf-multiple="true" ngf-max-size="'3GB'" ngf-max-total-size="'3GB'" ngf-allow-dir="true" ngf-keep="'distinct'"></div>

**Comment by danialfarid** [comment]
Fixed at version 11.0.1

**Comment by bgold0** [comment]
Thank you @danialfarid !!!!!!! Works perfectly now.

**Comment by bgold0** [comment]
@danialfarid it looks like you fixed the lag that happens when the file is added to the files array. However, in the background, the browser still freezes up and becomes unworkable with video files.
