### ISSUE TITLE
ngf-dimensions seem dependant on browser window size

### ISSUE THREAD

**Issue by dandanknight** [danialfarid/ng-file-upload#1368]
Hi,

I'm experiencing a strange issue whereby if I'm trying to validate an image that is larger than my browser window, then I get an validation error saying that the dimensions of the image are the size of my browser window.

For example, 

`
ngf-dimensions="$width === 1920 && $height === 1080"
`
..and loading in a 1920x1080 image will produce the following validation error....
````
{
    "$ngfBlobUrl": "blob:http%3A//localhost%3A3000/dac0927b-528c-408b-b875-7b7d86eca72e",
    "$ngfWidth": 1440,
    "$ngfHeight": 810,
    "$error": "dimensions",
    "$errorMessages": {
        "name": true
    },
    "$errorParam": false
}
````

If I reduce my browser window size, then the validation error dimensions change.

Any ideas how I can fix this? Many thanks

**Comment by dandanknight** [comment]
Also, using Upload.imageDimensions produces the same results, as I thought I may be able to use as a workaround, but it's seems not.

````
Upload.imageDimensions(file)
                .then(function(dimensions){
                    console.log(dimensions); // produces Object {width: 1440, height: 810}
                });
````

...and just for the sake of it, here's the media info to show the images actual dimensions.....

````
General
Complete name                            : arsenal_1920x1080.jpg
Format                                   : JPEG
File size                                : 290 KiB

Image
Format                                   : JPEG
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Compression mode                         : Lossy
Stream size                              : 290 KiB (100%)

````

**Comment by dandanknight** [comment]
OK, I've narrowed it down, and managed to reproduce the error in a plunk.

It seems that the error only occurs when some ui frameworks are introduced, in this case, the foundation css. 

So if you open the plunk, you'll see that the ngf-dimensions are set to validate for 1920x1080. If you don't have a 1920x1080 image to hand, there's a link to cone below. Choose the file in the plunk, and you see (provided that the plunker preview viewport width is less than 1920px) that the image fails validation and shows some erroneous fail dimensions. 

Now, if you try the plunk without the foundation.css (or just comment it out), it will work just fine. Strange eh? Any ideas anyone?

[1920x1080_picture](http://picpaste.com/pics/arsenal_1920x1024-7Mj304Eh.1455881732.jpg)

[Plunkr - Not working with foundation.css](https://plnkr.co/edit/HTdpY2srkDMDlO0Hjlf2?p=preview)

[Plunkr - Working with no css](https://plnkr.co/edit/5sEyfp4IyNh6GWBSX31k?p=preview)

**Comment by dandanknight** [comment]
Right, I know it seems I'm talking to myself here, but hopefully not! 

I've further narrowed it down to a single css entry....

````
img {
    max-width: 100%;
}
````

With it, the issue is there. Remove or set to none, and the issue is gone! Hopefully I can override in my app's css and get round this issue.

**Comment by danialfarid** [comment]
Fixed at 12.0.3

**Comment by hughred22** [comment]
I am having the exact same issue. And I am on 12.0.4 but the issue still there. In my case, I am using Angular Material (https://material.angularjs.org). Could you look into the issue and see what is going on? Thanks!

**Comment by hughred22** [comment]
BTW, I try to set 

      img {
	max-width: auto !important;
     }

on the entire page, it still does not solve the issue. My code: 
      Upload.imageDimensions($scope.file).then(function(dimensions){
		        		$scope.fileWidth = dimensions.width;
		        		$scope.fileHeight = dimensions.height;
		        	});

for the dimensions keep return the max of the browser window, but not the width of the upload file. Thank you!

**Comment by danialfarid** [comment]
@hughred22 what version of the plugin? what operating system and device?

**Comment by hughred22** [comment]
12.0.4 

I test this on Google Chrome latest version on a Mac.

**Comment by danialfarid** [comment]
@hughred22 could you create a jsfiddle with steps to reproduce.
