### ISSUE TITLE
fileElem.bind is not a function

### ISSUE THREAD

**Issue by abelkbil** [danialfarid/ng-file-upload#1673]
This isues arise even before using in agular, If add file shows this error.

angular.js:12520 TypeError: fileElem.bind is not a function
    at linkFileSelect (http://emi.local/javascripts/angular/ng-file-upload.js?v=0.2:851:14)
    at link (http://emi.local/javascripts/angular/ng-file-upload.js?v=0.2:920:7)
    at ea (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js?v=0.1:73:293)
    at D (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js?v=0.1:62:190)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js?v=0.1:55:105)
    at D (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js?v=0.1:62:134)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js?v=0.1:69:223
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js?v=0.1:119:129
    at r.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js?v=0.1:133:313)
    at r.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js?v=0.1:130:412) <button type="file" ngf-select="uploadFiles($file, $invalidFiles)" accept="image/*" ngf-max-height="1000" ngf-max-size="1MB">

```
var app 	= angular.module("app", ['ngFileUpload']);

app.controller("DocUploadController", ['$scope','uploadListService', function ($scope,uploadListService) {
	   $scope.filelist = doclist;
	   $scope.logcode = logcode;
	   $scope.unuploaded_section = false;
	   $scope.applicatnts_type = ['Main Applicant','Co Applicant -1 ','Co Applicant -2',];
	   $scope.current_applicant= $scope.applicatnts_type[0];

	   $scope.applicantchaged = function() {
	   		//$scope.filelist = null;
			//Promise code : not updating
	   		uploadListService.getFileList($scope.current_applicant)
	   		.then(
	            function (result) {
               		$scope.filelist = result;
	            	//$scope.$apply();	 
	            },
	            function (error) {
	            	alert(error.statusText);
	                console.log(error.statusText);
	            }
	        );
		}
	    
	}]);

app.directive("fileUploader", function() {
		return {
	        replace: true,
	        restrict: 'E', // Element directive
		    controller: ['$scope','Upload', function ($scope,Upload) { 
		    	$scope.upload = function (file) {
			    	 console.log('Start: ' + $scope.logcode );
			        Upload.upload({
			            url: 'https://angular-file-upload-cors-srv.appspot.com/upload',
			            data: {file: file, file_name:$scope.fileinfo.name, logcode:logcode}
			        }).then(function (resp) {
			            console.log('Success ' + resp.config.data.file.name + 'uploaded. Response: ' + resp.data);
			            $scope.fileinfo.status 		= 'Uploaded';
			            $scope.fileinfo.file_url 	= 'http://www.bennadel.com/images/header/photos/ryan_stewart.jpg';
			        }, function (resp) {
			            console.log('Error status: ' + resp.status);
			        }, function (evt) {
			            var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
			            //console.log('progress: ' + progressPercentage + '% ' + evt.config.data.file.name);
			        });
			    };
		    	$scope.div_visibility = function(parent_status,my_status,name){
			    	if(!parent_status&&my_status!='Uploaded'){
			    		console.log('++++++++++ : ' + my_status +name );
			    		return 'Set This div visible';
			    	}
			    };
		    }],
	        scope: { fileinfo: '=fileInfo',unuploaded_section:'=' },
	    	templateUrl: '/javascripts/angular/html/fileUploader.html'
	    };
	});

```

**Comment by danialfarid** [comment]
Can you create a jsfiddle? Demo and samples are working fine.

**Comment by abelkbil** [comment]
Thank you and appreciate for your consideration.
 
https://jsfiddle.net/abelkbil/k5a34exr/4/

**Comment by danialfarid** [comment]
The link doesn't work for me. I get injection error. You probably have not injected the module properly.

**Comment by abelkbil** [comment]
`var app = angular.module("app", ['ngFileUpload']);`

Above is module declaration, Actually I use it in directive template having a controller.

```
app.directive("fileUploader", function() {
		return {
	        replace: true,
	        restrict: 'E', // Element directive
		    controller: ['$scope','Upload', function ($scope,Upload) { 
		    	$scope.upload = function (file) {
			    	 console.log('Start: ' + $scope.logcode );
			        Upload.upload({
			            url: 'upload.php',
			            data: {file: file, file_name:$scope.fileinfo.name, logcode:logcode}
			        }).then(function (resp) {
			            console.log('Success ' + resp.config.data.file.name + 'uploaded. Response: ' + resp.data);
			            $scope.fileinfo.status 		= 'Uploaded';
			            $scope.fileinfo.file_url 	= 'http://www.bennadel.com/images/header/photos/ryan_stewart.jpg';
			        }, function (resp) {
			            console.log('Error status: ' + resp.status);
			        }, function (evt) {
			            var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
			            //console.log('progress: ' + progressPercentage + '% ' + evt.config.data.file.name);
			        });
			    };
		    	$scope.div_visibility = function(parent_status,my_status,name){
			    	if(!parent_status&&my_status!='Uploaded'){
			    		console.log('++++++++++ : ' + my_status +name );
			    		return 'Set This div visible';
			    	}
			    };
		    }],
	        scope: { fileinfo: '=fileInfo',unuploaded_section:'=' },
	        templateUrl: 'http://eemi.in/javascripts/angular/html/fileUploader.html'
	    };
	});
```
Is there any issue/mismatch in this.
I will update a working jsfiddle soon.

Thank you.

**Comment by danialfarid** [comment]
Well once you get rid of the injection error that shows up in the jsfiddle I will have a look. The injection issue is a general angular issue not related to this plugin. You can follow the jsfiddle sample in the docs to get you started.

**Comment by abelkbil** [comment]
This working jsfiddle . http://jsfiddle.net/abelkbil/9qw6fpsq/12/
Thanks for your support @danialfarid .
The issue was related to jquery v3 included. Changed jquery to 2.4 solved the issue.

Thank you again.
Abel J

**Comment by danialfarid** [comment]
Alright, so I assume the issue is resolved right?

**Comment by Nokel81** [comment]
I am still getting this error, does this mean that I cannot use jQuery v3?
