### ISSUE TITLE
How to display default image

### ISSUE THREAD

**Issue by ikhsan017** [danialfarid/ng-file-upload#725]
Hi There,

Just want to ask how to display default image when no file is selected, since ngf-src directive will always replace the src attribute

regards
Ikhsan

**Comment by ikhsan017** [comment]
I see it is located here

https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L529

can we make is so it is configurable?

**Comment by danialfarid** [comment]
Added `ngf-default-src` and validation: `ngf-accept, ngf-min-size, ngf-max-size' to the ngf-src directive in version 4.2.0

**Comment by ikhsan017** [comment]
Great, thanks :)

**Comment by pencilcheck** [comment]
Is there a way to make it accept a scope variable to ngf-default-src?? Right now the attribute is taken as the string directly, it is different from the README example where it uses single quote to signify its passing a string.

**Comment by danialfarid** [comment]
for now you can have `ngf-default-src="{{scopeVar}}"`

**Comment by kotakorange** [comment]
for now you can have ngf-default-src="{{scopeVar}}"
<< Not working this way

**Comment by danialfarid** [comment]
I think this is fixed, try with the latest version `ngf-default-src="scopeVar"`

**Comment by kotakorange** [comment]
try with the latest version ngf-default-src="scopeVar"
<< I used the latest version. and still no luck with this. Do you habe any other advice?

**Comment by richardthombs** [comment]
I can't get this to work with either a hardcoded URL, a quoted URL, or a scope variable with a URL in it.

This will take a regular, relative URL right, so I can have `ngf-default-src="/foo/bar.png"`?

**Comment by richardthombs** [comment]
@kotakorange As a workaround, I'm currently doing this:

`ngf-src="file || '/foo/bar.png'"`

This works for me because I'm only uploading a single file, not multiples, but you get the idea.

**Comment by danialfarid** [comment]
Fixed in version 6.0.3

**Comment by Fonger** [comment]
The bug still exists in 6.0.4

**Comment by richardthombs** [comment]
Are you sure? This is working for me:
```javascript
<img ngf-src="logo" ngf-default-src="original" ngf-accept="'image/*'">
```
Where`original` is scope variable containing a URL to an image, eg: `'/api/logos/6c683ed1-6615-45b5-8a63-bc4c00c05738'`

**Comment by danialfarid** [comment]
@Fonger could you create a jsfiddle.

**Comment by Fonger** [comment]
@richardthombs  @danialfarid 
Sorry, it's my fault. I think this is not a bug.
I found that my `ngf-default-src` is not loaded yet because my default src is fetched from API.

Something like this jsfiddle:
https://jsfiddle.net/ya0y6dy8/

Maybe I need 2-way binding, but I think this is not the best way.

Finally, I use the following code:
```js
<img ngf-src="file || work.pic" ngf-accept="'image/*'" style="width: 100%; height:auto;">
```

**Comment by danialfarid** [comment]
Using `ngf-src="file || defaultSrc"` seems to be a simpler approach than having another directive `ngf-default-src`. I am thinking to drop it in favor of `||` syntax  for the next version.

**Comment by danialfarid** [comment]
ngf-default-src is removed since version 6.2.0. Using || syntax would work. Some issues are also fixed,
