### ISSUE TITLE
'Don't make functions within the loop' + 'file is not defined'

### ISSUE THREAD

**Issue by dansurfs** [danialfarid/ng-file-upload#766]
Hey there,

I put in the controller code exactly as it is in the demo and JsHint gives me back 'Don't make functions within a loop.'
If I put the functions outside of the loop (besides perhaps breaking the intended functionality), I get back 'file is not defined.'

Have you heard of this happening before? Can you show how to fix this? I've seen some stuff on the web about it but don't know what to change within the controller.

Thanks a bunch.
Daniel

**Comment by danialfarid** [comment]
Should be fixed in 5.0.0

**Comment by deegale** [comment]
I know this is closed, but I was still getting "Don't make functions within the loop" error message from JsHint. I had made a batch upload page, following the example code in the readme. Here is what I needed to change to avoid the error JsHint warning. I'm adding this code here in case someone else googles and comes across this post like I did:

```js
  $scope.upload = function (files) {
      if (files && files.length) {
        for (var i = 0; i < files.length; i++) {
          var file = files[i];
          var studentId = file.name.split('.')[0];
          Upload.upload({
            url: 'admin/update/photo',
            fields: { 'id': studentId },
            file: file
          })
          .success(uploadGood)
          .error(uploadBad);
        }
      }
    };

  function uploadGood (data, status, headers, config) {
    // Handle the success
  }

  function uploadBad (data, status, headers, config) {
     // Handle the error
  }
```
