### ISSUE TITLE
Empty request payload/not sending binaries on Upload.http

### ISSUE THREAD

**Issue by nikkwong** [danialfarid/ng-file-upload#817]
Hi, I'm trying to POST my upload into an external DB, (mongolab in this case)—so I'm using the ```Upload.http``` method, with the following options:

                Upload.http({
                url: url, // my mongolab route
                data: JSON.stringify({ "objectData": file}),
                'Content-Type': 'application/json'
                })

When i send a file, the request payload is empty, or more specifically ```{0: {}}```. Am I missing something here? 

Many thanks

**Comment by danialfarid** [comment]
Is the `file` object an array or a single file, seems like you are sending an array it should be a single file

**Comment by nikkwong** [comment]
I'm just using the implementation as in the docs: 

    $scope.upload = function (files) {
           if (files && files.length) {
            for (var i = 0; i < files.length; i++) {
                var file = files[i];
                console.log(file);

                Upload.http({
                url: url, // upload.php script, node.js route, or servlet url
                data: JSON.stringify({ "objectData": file}),
                'Content-Type': 'application/json'
                })
       
    etc...

Where is the binary? I don't see it in the ```file``` object. Thanks for responding!

**Comment by danialfarid** [comment]
This is the example from the docs:
```
Upload.http({
            url: '/server/upload/url',
            headers : {
                'Content-Type': file.type
            },
            data: file
})
```
you shouldn't convert it to json

**Comment by nikkwong** [comment]
Yes, tried that initally, but in that case only an empty object is sent. Anything else I can try? Thanks for the help.

**Comment by danialfarid** [comment]
Fixed in version 5.0.6

**Comment by nikkwong** [comment]
I'm still having the issue. Is it confirmed fixed—? Maybe it is something on my end..

Thanks for the help.

**Comment by danialfarid** [comment]
The demo page should work now, just use the example from the docs.

**Comment by nikkwong** [comment]
Great! Is there any theoretical way to "see" the binary in the POST request? It should be in the ```data``` object right? I've done 

        if ((window.ArrayBuffer && data instanceof window.ArrayBuffer) || data instanceof Blob) {
          console.log(data);
          return data;

And only see the $$hashkey. Again, thank you for the help!
